apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pagc8bs9b-dotnet-basic 
  janus-idp.io/tekton: pagc8bs9b-dotnet-basic
  backstage.io/kubernetes-id: pagc8bs9b-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pagc8bs9b-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml